import { Jost } from "next/font/google";
import "./globals.css";

const jost = Jost({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Lok Mitra Kendra Hangloh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.className}>{children}</body>
    </html>
  );
}
